from src.config.kitti_model_config import kitti_model_config
from src.config.kitti_vgg16_config import kitti_vgg16_config
from src.config.kitti_res50_config import kitti_res50_config
from src.config.kitti_squeezeDet_config import kitti_squeezeDet_config
from src.config.kitti_squeezeDetPlus_config import kitti_squeezeDetPlus_config
